[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[meta-data]
name="pymiele"
version = "0.0.2"
author = "Ake Strandberg"
author_email = "ake@strandberg.eu"
description = "Library for Miele integration with Home Assistant"
long_description = "file: README.md"
long_description_content_type = "text/markdown"
url = "https://github.com/astrandb/pymiele"
project_urls = "Bug Tracker = https://github.com/astrandb/pymiele"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 4 - Beta",
]

[options]
package_dir = "pymiele"
packages = "find:"
python_requires = ">=3.9"
find = "pymiele"
# [options.packages.find]
# where = "src"

