name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # run on all branches
  release:
    types: [published]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version-file: pyproject.toml
      - run: ruff check --output-format=github
      - run: ruff format --check --respect-gitignore

    - name: Build package
      if: github.eventname =='release'
      run: python -m build

    - name: Publish package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.2.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
